// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ip4over6.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace OstProto {

namespace {

const ::google::protobuf::Descriptor* Ip4over6_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Ip4over6_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ip4over6_2eproto() {
  protobuf_AddDesc_ip4over6_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ip4over6.proto");
  GOOGLE_CHECK(file != NULL);
  Ip4over6_descriptor_ = file->message_type(0);
  static const int Ip4over6_offsets_[1] = {
  };
  Ip4over6_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Ip4over6_descriptor_,
      Ip4over6::default_instance_,
      Ip4over6_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Ip4over6, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Ip4over6, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Ip4over6));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ip4over6_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Ip4over6_descriptor_, &Ip4over6::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ip4over6_2eproto() {
  delete Ip4over6::default_instance_;
  delete Ip4over6_reflection_;
}

void protobuf_AddDesc_ip4over6_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::OstProto::protobuf_AddDesc_protocol_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016ip4over6.proto\022\010OstProto\032\016protocol.pro"
    "to\"\n\n\010Ip4over6:9\n\010ip4over6\022\022.OstProto.Pr"
    "otocol\030\260\002 \001(\0132\022.OstProto.Ip4over6", 113);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ip4over6.proto", &protobuf_RegisterTypes);
  Ip4over6::default_instance_ = new Ip4over6();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::OstProto::Protocol::default_instance(),
    304, 11, false, false,
    &::OstProto::Ip4over6::default_instance());
  Ip4over6::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ip4over6_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ip4over6_2eproto {
  StaticDescriptorInitializer_ip4over6_2eproto() {
    protobuf_AddDesc_ip4over6_2eproto();
  }
} static_descriptor_initializer_ip4over6_2eproto_;


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

Ip4over6::Ip4over6()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Ip4over6::InitAsDefaultInstance() {
}

Ip4over6::Ip4over6(const Ip4over6& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Ip4over6::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Ip4over6::~Ip4over6() {
  SharedDtor();
}

void Ip4over6::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Ip4over6::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Ip4over6::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Ip4over6_descriptor_;
}

const Ip4over6& Ip4over6::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ip4over6_2eproto();  return *default_instance_;
}

Ip4over6* Ip4over6::default_instance_ = NULL;

Ip4over6* Ip4over6::New() const {
  return new Ip4over6;
}

void Ip4over6::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Ip4over6::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void Ip4over6::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Ip4over6::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Ip4over6::ByteSize() const {
  int total_size = 0;
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Ip4over6::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Ip4over6* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Ip4over6*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Ip4over6::MergeFrom(const Ip4over6& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Ip4over6::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Ip4over6::CopyFrom(const Ip4over6& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ip4over6::IsInitialized() const {
  
  return true;
}

void Ip4over6::Swap(Ip4over6* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Ip4over6::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Ip4over6_descriptor_;
  metadata.reflection = Ip4over6_reflection_;
  return metadata;
}

::google::protobuf::internal::ExtensionIdentifier< ::OstProto::Protocol,
    ::google::protobuf::internal::MessageTypeTraits< ::OstProto::Ip4over6 >, 11, false >
  ip4over6(kIp4Over6FieldNumber, ::OstProto::Ip4over6::default_instance());

// @@protoc_insertion_point(namespace_scope)

}  // namespace OstProto

// @@protoc_insertion_point(global_scope)
