// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userscript.proto

#ifndef PROTOBUF_userscript_2eproto__INCLUDED
#define PROTOBUF_userscript_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "protocol.pb.h"
// @@protoc_insertion_point(includes)

namespace OstProto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_userscript_2eproto();
void protobuf_AssignDesc_userscript_2eproto();
void protobuf_ShutdownFile_userscript_2eproto();

class UserScript;

// ===================================================================

class UserScript : public ::google::protobuf::Message {
 public:
  UserScript();
  virtual ~UserScript();
  
  UserScript(const UserScript& from);
  
  inline UserScript& operator=(const UserScript& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserScript& default_instance();
  
  void Swap(UserScript* other);
  
  // implements Message ----------------------------------------------
  
  UserScript* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserScript& from);
  void MergeFrom(const UserScript& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string program = 1;
  inline bool has_program() const;
  inline void clear_program();
  static const int kProgramFieldNumber = 1;
  inline const ::std::string& program() const;
  inline void set_program(const ::std::string& value);
  inline void set_program(const char* value);
  inline void set_program(const char* value, size_t size);
  inline ::std::string* mutable_program();
  inline ::std::string* release_program();
  
  // @@protoc_insertion_point(class_scope:OstProto.UserScript)
 private:
  inline void set_has_program();
  inline void clear_has_program();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* program_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_userscript_2eproto();
  friend void protobuf_AssignDesc_userscript_2eproto();
  friend void protobuf_ShutdownFile_userscript_2eproto();
  
  void InitAsDefaultInstance();
  static UserScript* default_instance_;
};
// ===================================================================

static const int kUserScriptFieldNumber = 103;
extern ::google::protobuf::internal::ExtensionIdentifier< ::OstProto::Protocol,
    ::google::protobuf::internal::MessageTypeTraits< ::OstProto::UserScript >, 11, false >
  userScript;

// ===================================================================

// UserScript

// optional string program = 1;
inline bool UserScript::has_program() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserScript::set_has_program() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserScript::clear_has_program() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserScript::clear_program() {
  if (program_ != &::google::protobuf::internal::kEmptyString) {
    program_->clear();
  }
  clear_has_program();
}
inline const ::std::string& UserScript::program() const {
  return *program_;
}
inline void UserScript::set_program(const ::std::string& value) {
  set_has_program();
  if (program_ == &::google::protobuf::internal::kEmptyString) {
    program_ = new ::std::string;
  }
  program_->assign(value);
}
inline void UserScript::set_program(const char* value) {
  set_has_program();
  if (program_ == &::google::protobuf::internal::kEmptyString) {
    program_ = new ::std::string;
  }
  program_->assign(value);
}
inline void UserScript::set_program(const char* value, size_t size) {
  set_has_program();
  if (program_ == &::google::protobuf::internal::kEmptyString) {
    program_ = new ::std::string;
  }
  program_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserScript::mutable_program() {
  set_has_program();
  if (program_ == &::google::protobuf::internal::kEmptyString) {
    program_ = new ::std::string;
  }
  return program_;
}
inline ::std::string* UserScript::release_program() {
  clear_has_program();
  if (program_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = program_;
    program_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace OstProto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_userscript_2eproto__INCLUDED
