# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import protocol_pb2
import dot3_pb2
import llc_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='dot2llc.proto',
  package='OstProto',
  serialized_pb='\n\rdot2llc.proto\x12\x08OstProto\x1a\x0eprotocol.proto\x1a\ndot3.proto\x1a\tllc.proto\"\t\n\x07\x44ot2Llc:7\n\x07\x64ot2Llc\x12\x12.OstProto.Protocol\x18\xce\x01 \x01(\x0b\x32\x11.OstProto.Dot2Llc')


DOT2LLC_FIELD_NUMBER = 206
dot2Llc = descriptor.FieldDescriptor(
  name='dot2Llc', full_name='OstProto.dot2Llc', index=0,
  number=206, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_DOT2LLC = descriptor.Descriptor(
  name='Dot2Llc',
  full_name='OstProto.Dot2Llc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Dot2Llc'] = _DOT2LLC

class Dot2Llc(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOT2LLC
  
  # @@protoc_insertion_point(class_scope:OstProto.Dot2Llc)

dot2Llc.message_type = _DOT2LLC
protocol_pb2.Protocol.RegisterExtension(dot2Llc)
# @@protoc_insertion_point(module_scope)
