# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import protocol_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='hexdump.proto',
  package='OstProto',
  serialized_pb='\n\rhexdump.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"7\n\x07HexDump\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x1b\n\rpad_until_end\x18\x02 \x01(\x08:\x04true:6\n\x07hexDump\x12\x12.OstProto.Protocol\x18h \x01(\x0b\x32\x11.OstProto.HexDump')


HEXDUMP_FIELD_NUMBER = 104
hexDump = descriptor.FieldDescriptor(
  name='hexDump', full_name='OstProto.hexDump', index=0,
  number=104, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_HEXDUMP = descriptor.Descriptor(
  name='HexDump',
  full_name='OstProto.HexDump',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='content', full_name='OstProto.HexDump.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pad_until_end', full_name='OstProto.HexDump.pad_until_end', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['HexDump'] = _HEXDUMP

class HexDump(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEXDUMP
  
  # @@protoc_insertion_point(class_scope:OstProto.HexDump)

hexDump.message_type = _HEXDUMP
protocol_pb2.Protocol.RegisterExtension(hexDump)
# @@protoc_insertion_point(module_scope)
