# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import protocol_pb2
import ip4_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='ip4over4.proto',
  package='OstProto',
  serialized_pb='\n\x0eip4over4.proto\x12\x08OstProto\x1a\x0eprotocol.proto\x1a\tip4.proto\"\x10\n\x08Ip4over4*\x04\x08\x01\x10\x03:4\n\tip4_outer\x12\x12.OstProto.Ip4over4\x18\x01 \x01(\x0b\x32\r.OstProto.Ip4:4\n\tip4_inner\x12\x12.OstProto.Ip4over4\x18\x02 \x01(\x0b\x32\r.OstProto.Ip4:9\n\x08ip4over4\x12\x12.OstProto.Protocol\x18\xb1\x02 \x01(\x0b\x32\x12.OstProto.Ip4over4')


IP4_OUTER_FIELD_NUMBER = 1
ip4_outer = descriptor.FieldDescriptor(
  name='ip4_outer', full_name='OstProto.ip4_outer', index=0,
  number=1, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
IP4_INNER_FIELD_NUMBER = 2
ip4_inner = descriptor.FieldDescriptor(
  name='ip4_inner', full_name='OstProto.ip4_inner', index=1,
  number=2, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
IP4OVER4_FIELD_NUMBER = 305
ip4over4 = descriptor.FieldDescriptor(
  name='ip4over4', full_name='OstProto.ip4over4', index=2,
  number=305, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_IP4OVER4 = descriptor.Descriptor(
  name='Ip4over4',
  full_name='OstProto.Ip4over4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1, 3), ],
  serialized_start=55,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['Ip4over4'] = _IP4OVER4

class Ip4over4(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IP4OVER4
  
  # @@protoc_insertion_point(class_scope:OstProto.Ip4over4)

ip4_outer.message_type = ip4_pb2._IP4
Ip4over4.RegisterExtension(ip4_outer)
ip4_inner.message_type = ip4_pb2._IP4
Ip4over4.RegisterExtension(ip4_inner)
ip4over4.message_type = _IP4OVER4
protocol_pb2.Protocol.RegisterExtension(ip4over4)
# @@protoc_insertion_point(module_scope)
