# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import protocol_pb2
import gmp_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='mld.proto',
  package='OstProto',
  serialized_pb='\n\tmld.proto\x12\x08OstProto\x1a\x0eprotocol.proto\x1a\tgmp.proto:/\n\x03mld\x12\x12.OstProto.Protocol\x18\x94\x03 \x01(\x0b\x32\r.OstProto.Gmp')


MLD_FIELD_NUMBER = 404
mld = descriptor.FieldDescriptor(
  name='mld', full_name='OstProto.mld', index=0,
  number=404, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


mld.message_type = gmp_pb2._GMP
protocol_pb2.Protocol.RegisterExtension(mld)
# @@protoc_insertion_point(module_scope)
