# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import protocol_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='userscript.proto',
  package='OstProto',
  serialized_pb='\n\x10userscript.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"\x1d\n\nUserScript\x12\x0f\n\x07program\x18\x01 \x01(\t:<\n\nuserScript\x12\x12.OstProto.Protocol\x18g \x01(\x0b\x32\x14.OstProto.UserScript')


USERSCRIPT_FIELD_NUMBER = 103
userScript = descriptor.FieldDescriptor(
  name='userScript', full_name='OstProto.userScript', index=0,
  number=103, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_USERSCRIPT = descriptor.Descriptor(
  name='UserScript',
  full_name='OstProto.UserScript',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='program', full_name='OstProto.UserScript.program', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['UserScript'] = _USERSCRIPT

class UserScript(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERSCRIPT
  
  # @@protoc_insertion_point(class_scope:OstProto.UserScript)

userScript.message_type = _USERSCRIPT
protocol_pb2.Protocol.RegisterExtension(userScript)
# @@protoc_insertion_point(module_scope)
